apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-vars
data:
  grafana_user: admin
  grafana_password: password
  monitored_hosts: 
    - 192.168.196.208
    - 192.168.196.64

  snmp_modules:
    - if_mib
    - ucd_snmp_mib

  blackbox_modules:
    - icmp
